service: foo-serverless-backend

frameworkVersion: ">=2.52.1"

useDotenv: true

custom:
  prod:
    Stack: foo-serverless
    LogLevel: info
  dev:
    Stack: foo-serverless
    LogLevel: debug
    
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 10
  region: ${env:FOO_AWS_REGION, 'ap-southeast-1'}
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 14
  environment:
    logLevel: ${self:custom.${self:provider.stage}.LogLevel}
    
package:
  individually: true
  
resources:
  - ${file(resources/apigateway/RestApi.yml)}
  - ${file(resources/dynamodb/TableA.yml)}
  - ${file(resources/dynamodb/TableB.yml)}
  - Outputs:
      ApiGWRestApiId:
        Value:
          Ref: ApiGatewayRestApi
        Export:
          Name: ${self:custom.${self:provider.stage}.Stack}-restApiId-${self:provider.stage}
      ApiGWRootResourceId:
        Value:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        Export:
          Name: ${self:custom.${self:provider.stage}.Stack}-rootResourceId-${self:provider.stage}
          
plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-reducer
  - serverless-offline
